-- {
--   "ResponseID": 0,
--   "Message": "Roles security List",
--   "Roles": [
--       {
--           "Name": "read",
--           "Privileges": [
--               {
--                   "Name": "read",
--                   "Database": "*",
--                   "Table": "*"
--               }
--           ]
--       },
--       {
--           "Name": "readwrite",
--           "Privileges": [
--               {
--                   "Name": "read",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "insert",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "update",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "delete",
--                   "Database": "*",
--                   "Table": "*"
--               }
--           ]
--       },
--       {
--           "Name": "readwriteanydatabase",
--           "Privileges": [
--               {
--                   "Name": "read",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "insert",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "update",
--                   "Database": "*",
--                   "Table": "*"
--               },
--               {
--                   "Name": "delete",
--                   "Database": "*",
--                   "Table": "*"
--               }
--           ]
--       }
--   ]
-- }