-- {
--   "ResponseID": 0,
--   "Message": "Nodes List",
--   "Nodes": [
--       {
--           "Name": "Node 1",
--           "Address": "207.142.84.10",
--           "Status": "Replicating",
--           "Details": "SFO1/1GB/25GB disk",
--           "Raft": [
--               8960,
--               8960
--           ],
--           "Load": [
--               11,
--               0.3
--           ],
--           "Cpu": {
--               "Used": 1000,
--               "Total": 2400
--           },
--           "Ram": {
--               "Used": 2400,
--               "Total": 8000
--           },
--           "Type": "Leader",
--           "Coordinates": {
--               "Lat": 41.902782,
--               "Lng": 12.496366
--           }
--       },
--       {
--           "Name": "Node 2",
--           "Address": "207.142.84.10",
--           "Status": "Replicating",
--           "Details": "SFO1/1GB/25GB disk",
--           "Raft": [
--               8960,
--               8960
--           ],
--           "Load": [
--               11,
--               0.3
--           ],
--           "Cpu": {
--               "Used": 1000,
--               "Total": 2400
--           },
--           "Ram": {
--               "Used": 2400,
--               "Total": 8000
--           },
--           "Type": "Leader",
--           "Coordinates": {
--               "Lat": 41.902782,
--               "Lng": 12.496366
--           }
--       }
--   ]
-- }