-- {
--   "ResponseID": 0,
--   "Message": "Users security List",
--   "Users": [
--       {
--           "Name": "admin",
--           "Roles": [
--               {
--                   "Name": "admin",
--                   "Database": "*",
--                   "Table": "*"
--               }
--           ]
--       },
--       {
--           "Name": "Marco",
--           "Roles": [
--               {
--                   "Name": "read",
--                   "Database": "db1",
--                   "Table": "*"
--               },
--               {
--                   "Name": "readwrite",
--                   "Database": "db2",
--                   "Table": "table1"
--               },
--               {
--                   "Name": "read",
--                   "Database": "db3",
--                   "Table": "*"
--               }
--           ]
--       },
--       {
--           "Name": "Andrea",
--           "Roles": [
--               {
--                   "Name": "clustermonitor",
--                   "Database": "*",
--                   "Table": "*"
--               }
--           ]
--       }
--   ]
-- }